import Link from 'next/link';
import React from 'react';

function Head() {
  return (
    <>
      <title>Next.js 13 | Blog</title>
      <meta name='description' content='Generated by create next app' />
      <Link rel='icon' href='/favicon.ico' />
    </>
  )
}

export default Head;
